apiVersion: v1
kind: Service
metadata:
  name: sukt-ocelot-gateway-service
  namespace: etlbigdataservice
spec:
  type: NodePort
  selector:
    app: suktocelot-gateway-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30600
